GFGSC-RTU/GFG-SDE-Sheet-Solution-Kit

- Solutions/Cutting a Rod
Added Solution to Cutting a Rod GFG-SDE-Sheet questions in cpp
> Added Solution to Cutting a Rod GFG-SDE-Sheet questions in cpp

- Solutions/Reversearrayingroups.py
Reverse array in groups using python
> Reversearrayingroups.py

- Solutions/Trapping-rain-water
Hey, there I just added the solution to the Rain Water Trapping problem.
> Adding solution for Trapping rain Water problem

- Solutions/CeilInBST.java
Hello
I have added Ceil in bst problem in java
Please Merge the Request with hacktoberfest-accepted tag
Thanks !!
> add ceilInBst problem in Java

- Solutions/Rearrange an array with O(1) extra space.cpp
Solution of Rearrange an array with O(1) extra space.
> changes made

- Solutions/CheckIfTwoArraysAreEqualOrNot.cpp
Hey 
I have solves check if two arrays are equal or not.
Please Merge the Request 
Thanks !!
> Addedsolution-check if two arrays are equal or not

- Solutions/03_LevelOrderTraversal.cpp
This is code for level order traversal of tree using queue
> level order traversal

- Solutions/Rearrange_array_alternately.py
Solution to : https://www.geeksforgeeks.org/rearrange-array-maximum-minimum-form/
> Solution to rearrange array alternately

- Solutions/Remove Duplicates from Sorted List
Remove Duplicates from Sorted List from gfg sde
> Create Remove Duplicates from Sorted List

- Solutions/Maximum_path_sum_tree_leaf2leaf.cpp
Accept this PR under hacktoberfest accepted tag
> Maximum Path Sum between 2 Leaf Nodes

- Solutions/Find_the_missing_number.cpp
Added code for Finding the missing number problem
> Added code for Find the missing number problem

- Solutions/allocating_minimum_number_of_pages.cpp
Allocating minimum number of pages such that the maximum number of pages assigned to a student is minimum using binary search algorithm.
> Added allocating minimum number of pages problem

- Solutions/Array_subset_of_another_array.cpp
The solution to the Array subset of another array question is added in CPP.
> Created Array_subset_of_another_array.cpp

- Solutions/Palindrome Pair
> Create Palindrome Pair

- Solutions/Greedy-Approach-Activity-Selection.cpp
Greedy Approach Activity Selection in cpp
> Greedy Approach Activity Selection

- Solutions/Spirally_traversing_a_matrix.java
I've added "Spirally traversing a 2D array" program in java
> Added Spirally traversing a 2D array

- BinarySearch.c
> C program for BinarySearch

- Solutions/Heap_Rearrange_characters.java
Added Rearrange characters in heap java
> Heap Rearrange characters

- Solutions/Graph_depth_first_traversal.c
Create depth first traversal in c
> Graph depth first traversal

- Solutions/Top_view_of_binary_tree.cpp
Hi i have added a solution of Top View of Binary Tree
> Top View of a Binary Tree

- Solutions/CountInversionInArray.java
> Added Count inversions in an array (Merge Sort)

- Integer to Roman
solution of Integer to Roman problem in CPP.
> Integer to Roman.cpp

- Solutions/Delete Node in a Linked List
Solution of Delete Node in a Linked List in CPP.
> Delete Node in a Linked List.cpp

- Solutions/DiameterOfATree.cpp
> Diameter of a Tree Cpp solution added

- Solutions/Count Inversions.cpp
- Solutions/DiameterOfATree.cpp
used merge sort. Hope you liked the solution.
> Count inversion

- Solutions/LCA_in_a_Binary_Tree.cpp
- Solutions/Top_view_of_binary_tree.cpp
Hi, I have added solution of LCA in a Binary Tree
> LCA in a Binary Tree

- Solutions/LCA_in_a_Binary_Tree.cpp
- Solutions/Top_view_of_binary_tree.cpp
- Solutions/Zig_Zag_Traversal_in_a_Binary_Tree.cpp
Hi, I have added solution of Zig Zag Traversal of a Binary Tree
> Zig Zag Traversal of A binary Tree

- Solutions/Delete_a_node_in_a_BST.cpp
- Solutions/LCA_in_a_Binary_Tree.cpp
- Solutions/Top_view_of_binary_tree.cpp
- Solutions/Zig_Zag_Traversal_in_a_Binary_Tree.cpp
Hi, I have added solution of Delete a node in BST
> Delete a Node in a BST

- Solutions/job_sequencing.cpp
Created job_sequencing.cpp please review the code and merge it. @gfg-rtu
> Created job_sequencing.cpp

- Combination Sum II
Solution of leetcode problem Combination Sum II in CPP.
> Combination Sum II.cpp

- Rotate matrix elements clockwise.cpp
It is a gfg sheet problem solution in c++
> Rotate matrix elements clockwise

- Solutions/LargestNumberFromArray.java
I've added java solution for largest number formed from an array
> Added Largest number formed from an array in java

- Solutions/RelativeSorting.java
I've added java solution for relative sorting
> Added Relative sorting

- Solutions/Rotten_Oranges_Solution.cpp
@gfg-rtu Kindly review my PR under HacktoberFest 2022.
> Rotten Oranges Solution Submitted.

- .vscode/settings.json
- Solutions/Rat-Maze Problem.cpp
@gfg-rtu Kindly review my PR under Hacktoberfest 2022.
> Submitted Rat-Maze problem code in C++.

- Solutions/traveling_salesman.cpp
I have added code for travelling salesman problem please review it and merge it @gfg-rtu
> added travelling salesman algorithm

- Solutions/Rabin-Karp Algorithm for Pattern Searching.cpp
@gfg-rtu Kindly review my PR under Hacktoberfest 2022.
> Rabin-Karp Algorithm for Pattern Searching

- Solutions/snake ladder problem.cpp
@gfg-rtu Kindly review my updated PR under Hacktoberfest 2022.
> Snake Ladder Problem Solution Code.

- Solutions/Rat_in_a_maze_problem.cpp
> Added_Rat_in_a_maze_problem.cpp 

- Solutions/bubble_sort.cpp
I have added bubble sort algorithm @gfg-rtu please review my pull request.
> added bubble_sort.cpp

- Solutions/Dutch_National_Flag_Algo.cpp
- Solutions/shortest_hamiltonian.cpp
@gfg-rtu  Added Shortest Hamiltonian Path in weighted digraph
> Added shortest_hamiltonian.cpp

- Solutions/Dutch_National_Flag_Algo.cpp
- Solutions/shortest_hamiltonian.cpp
> Added Dutch_National_Flag_Algo

- Minimum_Spanning_Tree.cpp
> Added Minimum Spanning Tree.cpp

- Solutions/rotate_matrix.cpp
> added rotate_matrix.cpp

- Solutions/encrypt_sentence.py
**Problem Statement**
Write a python function, encrypt_sentence() which accepts a message and encrypts it based on rules given below and returns the encrypted message.
Words at odd position -> Reverse It
Words at even position -> Rearrange the characters so that all consonants appear before the vowels and their order should not change
Please do put the 'Hacktoberfest-accepted' label if you merge this PR
> Added encrypt_sentence program in python

- Solutions/3. Number of Provinces.cpp
- Solutions/4. Number of islands.cpp
- Solutions/5. Flood Fill.cpp
> Graph some files added

- Solutions/C/KadaneAlgorithm.c
Added solution to Kadane's Algorithm in c .
Please merge it
> KadaneAlgorithm.c

- Solutions/CPP/merged_intervals_overlapping.cpp
- Solutions/CPP/neon_number.cpp
created neon_number.cpp file in cpp folder. @gfg-rtu please review my PR
> Dawn coder1518 patch 1

- Solutions/CPP/merged_intervals_overlapping.cpp
> created merged_intervals_overlapping.cpp

- Solutions/Java/Rotate-matrix-elements-clockwise.java
Solution of Rotate matrix elements clockwise; The first question under Matrix subsection in GFG SDE Sheet
> Rotate matrix elements clockwise in java

- Solutions/C++/CPP/Maximize Toys
Solution of problem Maximize Toys 
Problem Link: https://www.geeksforgeeks.org/sde-sheet-a-complete-guide-for-sde-preparation/#Greedy
> Create Maximize Toys

- Solutions/C++/CPP/K-th bit.cpp
Added program  to Set the K-th bit of a given number
> Create K-th bit.cpp

- Solutions/C++/CPP/Remove_Duplicates_from_unsorted_linked_list.cpp
> Created Remove_Duplicates_from_unsorted_linked_list.cpp

- Solutions/C++/CPP/Remove_nodes_with_value_k.cpp
@gfg-rtu Please review and merge
> Created Remove_nodes_with_value_k.cpp
